AllCops:
  Exclude:
    - db/schema.rb
    - vendor/bundle/**/*

  Include:
    - '**/*.builder'
    - '**/*.jbuilder'
    - '**/*.rake'
    - '**/config.ru'
    - '**/Gemfile'
    - '**/Rakefile'
    - '**/Capfile'
    - '**/Vagrantfile'

  DisplayCopNames: true

  DisplayStyleGuide: true

#
# @todo: Decide on a better default than 25 and reenable. 25 is science-fiction
# for a Rails app, specially if it uses gems like activeadmin.
#
Metrics/BlockLength:
  Enabled: false

Performance/Casecmp:
  Enabled: false

Style/Lambda:
  Enabled: false

Style/ModuleFunction:
  EnforcedStyle: extend_self

Rails:
  Enabled: true

#
# @todo Enable when we migrate to Rails 5 or when
# https://github.com/bbatsov/rubocop/issues/3629 is fixed.
#
Rails/HttpPositionalArguments:
  Enabled: false

inherit_from: .rubocop_todo.yml
