# .travis.yml
language: ruby
cache: bundler
rvm:
  - 2.0.0
script:
  - RAILS_ENV=test bundle exec rake db:schema:load --trace
  - bundle exec rake db:test:prepare
  - bundle exec rake
before_script:
  - cp config/app_config.yml.example config/app_config.yml

