# .travis.yml
language: ruby
cache: bundler
rvm:
  - 2.0.0
before_install:
  - gem update --system
  - sudo apt-get install sphinxsearch
script:
  - RAILS_ENV=test bundle exec rake db:schema:load --trace
  - bundle exec rake db:test:prepare
  - bundle exec rake
before_script:
  - cp config/app_config.yml.example config/app_config.yml
env:
  - DATABASE=mysql2 SPHINX_BIN=/usr/bin/ SPHINX_VERSION=2.0.4
