---

language: ruby

cache:
  bundler: true

services:
  - redis-server

rvm:
  - 2.3.1

before_install:
  - gem update --system
  - gem install bundler

script:
  - RAILS_ENV=test bin/rake db:drop db:create db:schema:load
  - bin/rake download_maxmind_db
  - bin/rake

before_script:
  - cp config/secrets.yml.example config/secrets.yml
  - cp config/database.yml.travis config/database.yml

branches:
  only:
    - master
