# .travis.yml
language: ruby
cache: bundler
rvm:
  - 2.0.0
before_install:
  - gem update --system
  - curl -O http://fs-packages.s3.amazonaws.com/fs-sphinx-2.0.6_x86_64_12.04.deb
  - sudo dpkg -i fs-sphinx-2.0.6_x86_64_12.04.deb
script:
  - RAILS_ENV=test bundle exec rake db:schema:load --trace
  - bundle exec rake db:test:prepare
  - bundle exec rake
before_script:
  - cp config/app_config.yml.example config/app_config.yml
env:
  - DATABASE=mysql2 SPHINX_BIN=/usr/local/sphinx-2.0.6/bin/ SPHINX_VERSION=2.0.6
