defaults: &defaults
  secret_token: <%= ENV['NLT_SECRET_TOKEN'] %>
  secret_key_base: <%= ENV['NLT_SECRET_KEY_BASE'] %>

development:
  <<: *defaults

test:
  <<: *defaults

staging:
  <<: *defaults

production:
  <<: *defaults
